# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github

    - name: Build with Maven
      run: bash -c "mvn -Dmaven.test.skip=true -B package --file pom.xml ; exit 0"

    - name: Upload Api File
      uses: actions/upload-artifact@v4
      with:
        name: Api
        path: api/target/*.jar
        retention-days: 7
    - name: Upload Plugin File
      uses: actions/upload-artifact@v4
      with:
        name: Plugin
        path: plugin/target/*.jar
        retention-days: 7